refactor: policies, pushed requests and ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,12 +12,12 @@ jobs:
 
       - uses: actions/setup-go@v4
         with:
-          go-version-file: 'go.mod'
+          go-version-file: "go.mod"
 
       - name: Lint
-        uses: golangci/golangci-lint-action@v6
+        uses: golangci/golangci-lint-action@v7
         with:
-          version: v1.59
+          version: v2.1.6
 
       - name: Vet
         run: |
@@ -30,16 +30,16 @@ jobs:
 
       - name: Quality Gate
         env:
-            TEST_COVERAGE_THRESHOLD: 60
+          TEST_COVERAGE_THRESHOLD: 60
         run: |
-              echo "Quality Gate: checking test coverage is above threshold ..."
-              echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
-              totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
-              echo "Current test coverage : $totalCoverage %"
-              if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
-                  echo "OK"
-              else
-                  echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-                  echo "Failed"
-                  exit 1
-              fi
+          echo "Quality Gate: checking test coverage is above threshold ..."
+          echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
+          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+          echo "Current test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
+              echo "OK"
+          else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Failed"
+              exit 1
+          fi
